<?php

namespace Database\Seeders;

use App\Models\Spmiindikatorsub;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpmiindikatorsubSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'spmi_indikators_id' => 6,
                'kode' => 'A',
                'indikatorsub' => '[Sistem Tata Pamong] Kelengkapan struktur organisasi dan keefektifan penyelenggaraan organisasi',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'spmi_indikators_id' => 6,
                'kode' => 'B',
                'indikatorsub' => '[Sistem Tata Pamong] Perwujudan good governance dan pemenuhan lima pilar sistem tata pamong, yang mencakup: 1) Kredibel, 2) Transparan, 3) Akuntabel, 4) Bertanggung jawab, 5) Adil.	',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'spmi_indikators_id' => 7,
                'kode' => 'A',
                'indikatorsub' => '[Kepemimpinan dan Kemampuan Manajerial] Komitmen pimpinan UPPS.',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'spmi_indikators_id' => 7,
                'kode' => 'B',
                'indikatorsub' => '[Kepemimpinan dan Kemampuan Manajerial] Kapabilitas pimpinan UPPS, mencakup aspek: 1) perencanaan, 2) pengorganisasian, 3) penempatan personel, 4) pelaksanaan, 5) pengendalian dan pengawasan, dan 6) pelaporan yang menjadi dasar tindak lanjut. ',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'spmi_indikators_id' => 9,
                'kode' => 'A',
                'indikatorsub' => '[Kerjasama [Data]] Kerjasama perguruan tinggi di bidang pendidikan, penelitian dan PkM dalam 3 tahun terakhir.Tabel 1 LKPS ',
                'asal' => '',
                'rumus' => 'RK = ((a x N1) + (b x N2) + (c x N3)) / NDT',
                'keterangan' => 'N1 = Jumlah kerjasama pendidikan. | N2 = Jumlah kerjasama penelitian.	| N3 = Jumlah kerjasama pengabdian kepada masyarakat.	| NDTPS = Jumlah dosen tetap yang ditugaskan sebagai pengampu mata kuliah dengan bidang keahlian yang sesuai dengan kompetensi inti program studi yang diakreditasi.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'spmi_indikators_id' => 9,
                'kode' => 'B',
                'indikatorsub' => '[Kerjasama [Data]] B. Kerjasama tingkat internasional, nasional, wilayah/lokal yang relevan dengan program studi dan dikelola oleh UPPS dalam 3 tahun terakhir. Tabel 1 LKPS',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '4: NI ≥ a | 3-4: NI < a DAN NN ≥ b | 2-3: 0 < NI < a DAN 0 < NN < b | 2: NI = 0 DAN NN = 0 DAN NW ≥ c | 0-2: NI = 0 DAN NN = 0 DAN NW < c',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'spmi_indikators_id' => 14,
                'kode' => '0',
                'indikatorsub' => 'Pilih kelompok program studi berdasarkan jumlah kebutuhan lulusan sesuai pilihan yang tersedia. 1: Tinggi; 2: Rendah.',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'spmi_indikators_id' => 14,
                'kode' => '1',
                'indikatorsub' => 'Untuk program studi dengan jumlah kebutuhan lulusan tinggi berlaku perhitungan Skor sebagai berikut:	',
                'asal' => '',
                'rumus' => 'Rasio = NA / NB',
                'keterangan' => 'NA = Jumlah calon mahasiswa yang ikut seleksi.	| NB = Jumlah calon mahasiswa yang lulus seleksi.	',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'spmi_indikators_id' => 14,
                'kode' => '1',
                'indikatorsub' => 'Untuk program studi dengan jumlah kebutuhan lulusan rendah berlaku pemberian Skor sesuai kondisi berikut:',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'spmi_indikators_id' => 15,
                'kode' => 'A',
                'indikatorsub' => 'Peningkatan animo calon mahasiswa. Tabel 2.a LKPS',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'spmi_indikators_id' => 15,
                'kode' => 'B',
                'indikatorsub' => 'Mahasiswa asing Tabel 2.b LKPS',
                'asal' => '',
                'rumus' => 'PMA = (NMAFT + NMAPT) / NMUPPS',
                'keterangan' => 'NMUPPS = Jumlah mahasiswa aktif di UPPS dalam 3 tahun terakhir (TS-2 s.d. TS).	| NMAFT = Jumlah mahasiswa asing penuh waktu dalam 3 tahun terakhir (TS-2 s.d. TS)	| NMAPT = Jumlah mahasiswa asing paruh waktu dalam 3 tahun terakhir (TS-2 s.d. TS)',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'spmi_indikators_id' => 16,
                'kode' => 'A',
                'indikatorsub' => 'A. Ketersediaan layanan kemahasiswaan di bidang',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '1) penalaran, minat dan bakat, 2) kesejahteraan (bimbingan dan konseling, layanan beasiswa, dan layanan kesehatan), dan 3) bimbingan karir dan kewirausahaan.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'spmi_indikators_id' => 16,
                'kode' => 'B',
                'indikatorsub' => 'B. Akses dan mutu layanan kemahasiswaan.	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'spmi_indikators_id' => 31,
                'kode' => 'A',
                'indikatorsub' => 'Kualifikasi dan kecukupan tenaga kependidikan berdasarkan jenis pekerjaannya (administrasi, pustakawan, teknisi, dll.)	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => 'Catatan: Penilaian kecukupan tidak hanya ditentukan oleh jumlah tenaga kependidikan, namun keberadaan dan pemanfaatan teknologi informasi dan komputer dalam proses administrasi dapat dijadikan pertimbangan untuk menilai efektifitas pekerjaan dan kebutuhan akan tenaga kependidikan.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'spmi_indikators_id' => 31,
                'kode' => 'B',
                'indikatorsub' => 'Akses dan mutu layanan kemahasiswaan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'spmi_indikators_id' => 38,
                'kode' => 'A',
                'indikatorsub' => 'Keterlibatan pemangku kepentingan dalam proses evaluasi dan pemutakhiran kurikulum.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'spmi_indikators_id' => 38,
                'kode' => 'B',
                'indikatorsub' => 'Kesesuaian capaian pembelajaran dengan profil lulusan dan jenjang KKNI/SKKNI.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'spmi_indikators_id' => 38,
                'kode' => 'C',
                'indikatorsub' => 'Ketepatan struktur kurikulum dalam pembentukan capaian pembelajaran.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'spmi_indikators_id' => 40,
                'kode' => 'A',
                'indikatorsub' => 'Ketersediaan dan kelengkapan dokumen rencana pembelajaran semester (RPS) ',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'spmi_indikators_id' => 40,
                'kode' => 'B',
                'indikatorsub' => 'Kedalaman dan keluasan RPS sesuai dengan capaian pembelajaran lulusan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'spmi_indikators_id' => 41,
                'kode' => 'A',
                'indikatorsub' => 'Bentuk interaksi antara dosen, mahasiswa dan sumber belajar',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'spmi_indikators_id' => 41,
                'kode' => 'B',
                'indikatorsub' => 'Pemantauan kesesuaian proses terhadap rencana pembelajaran',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'spmi_indikators_id' => 41,
                'kode' => 'C',
                'indikatorsub' => 'Proses pembelajaran yang terkait dengan penelitian harus mengacu SN Dikti Penelitian: 1) hasil penelitian: harus memenuhi pengembangan IPTEKS, meningkatkan kesejahteraan masyarakat, dan daya saing bangsa. 2) isi penelitian: memenuhi kedalaman dan keluasan materi penelitian sesuai capaian pembelajaran. 3) proses penelitian: mencakup perencanaan, pelaksanaan, dan pelaporan. 4) penilaian penelitian memenuhi unsur edukatif, obyektif, akuntabel, dan transparan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'spmi_indikators_id' => 41,
                'kode' => 'D',
                'indikatorsub' => 'Proses pembelajaran yang terkait dengan PkM harus mengacu SN Dikti PkM: 1) hasil PkM: harus memenuhi pengembangan IPTEKS, meningkatkan kesejahteraan masyarakat, dan daya saing bangsa. 2) isi PkM: memenuhi kedalaman dan keluasan materi PkM sesuai capaian pembelajaran. 3) proses PkM:  mencakup perencanaan, pelaksanaan, dan pelaporan. 4) penilaian PkM memenuhi unsur edukatif, obyektif, akuntabel, dan transparan',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'spmi_indikators_id' => 41,
                'kode' => 'E',
                'indikatorsub' => 'Kesesuaian metode pembelajaran dengan capaian pembelajaran. Contoh: RBE (research based education), IBE (industry based education), teaching factory/teaching industry, dll.	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'spmi_indikators_id' => 44,
                'kode' => 'A',
                'indikatorsub' => 'Mutu pelaksanaan penilaian pembelajaran (proses dan hasil belajar mahasiswa) untuk mengukur ketercapaian capaian pembelajaran berdasarkan prinsip penilaian yang mencakup: 1) edukatif, 2) otentik, 3) objektif, 4) akuntabel, dan 5) transparan, yang dilakukan secara terintegrasi',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'spmi_indikators_id' => 44,
                'kode' => 'B',
                'indikatorsub' => 'Pelaksanaan penilaian terdiri atas teknik dan instrumen penilaian. Teknik penilaian terdiri dari: 1) observasi, 2) partisipasi, 3) unjuk kerja, 4) test tertulis, 5) test lisan, dan 6) angket. Instrumen penilaian terdiri dari: 1) penilaian proses dalam bentuk rubrik, dan/ atau; 2) penilaian hasil dalam bentuk portofolio, atau 3) karya disain."	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'spmi_indikators_id' => 44,
                'kode' => 'C',
                'indikatorsub' => 'Pelaksanaan penilaian memuat unsur-unsur sebagai berikut: 1) mempunyai kontrak rencana penilaian, 2) melaksanakan penilaian sesuai kontrak atau kesepakatan, 3) memberikan umpan balik dan memberi kesempatan untuk mempertanyakan hasil kepada mahasiswa, 4) mempunyai dokumentasi penilaian proses dan hasil belajar mahasiswa, 5) mempunyai prosedur yang mencakup tahap perencanaan, kegiatan pemberian tugas atau soal, observasi kinerja, pengembalian hasil observasi, dan pemberian nilai akhir, 6) pelaporan penilaian berupa kualifikasi keberhasilan mahasiswa dalam menempuh suatu mata kuliah dalam bentuk huruf dan angka, 7) mempunyai bukti-bukti rencana dan telah melakukan proses perbaikan berdasar hasil monev penilaian.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'spmi_indikators_id' => 47,
                'kode' => 'A',
                'indikatorsub' => 'Tingkat kepuasan mahasiswa terhadap proses pendidikan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => 'Tabel 5.c LKPS Aspek yang diukur: 1) Keandalan (reliability): kemampuan dosen, tenaga kependidikan, dan pengelola dalam memberikan pelayanan; 2) Daya tanggap (responsiveness): kemauan dari dosen, tenaga kependidikan, dan pengelola dalam membantu mahasiswa dan memberikan jasa dengan cepat; 3) Kepastian (assurance): kemampuan dosen, tenaga kependidikan, dan pengelola untuk memberi keyakinan kepada mahasiswa bahwa pelayanan yang diberikan telah sesuai dengan ketentuan; 4) Empati (empathy): kesediaan/kepedulian dosen, tenaga kependidikan, dan pengelola untuk memberi perhatian kepada mahasiswa; dan 5) Tangible: penilaian mahasiswa terhadap kecukupan, aksesibitas, kualitas sarana dan prasarana.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'spmi_indikators_id' => 47,
                'kode' => 'B',
                'indikatorsub' => 'Analisis dan tindak lanjut dari hasil pengukuran kepuasan mahasiswa.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'spmi_indikators_id' => 80,
                'kode' => 'A',
                'indikatorsub' => 'Metoda rekrutmen dan sistem seleksi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'spmi_indikators_id' => 80,
                'kode' => 'B',
                'indikatorsub' => 'Kriteria penerimaan mahasiswa.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'spmi_indikators_id' => 80,
                'kode' => 'C',
                'indikatorsub' => 'Proses seleksi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'spmi_indikators_id' => 81,
                'kode' => 'A',
                'indikatorsub' => '"Ketersediaan layanan kemahasiswaan dalam bentuk: 1) bimbingan dan konseling, 2) layanan beasiswa, dan 3) layanan kesehatan."',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'spmi_indikators_id' => 81,
                'kode' => 'B',
                'indikatorsub' => 'Akses dan mutu layanan kemahasiswaan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'spmi_indikators_id' => 82,
                'kode' => 'A',
                'indikatorsub' => 'Metoda rekrutmen.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'spmi_indikators_id' => 82,
                'kode' => 'B',
                'indikatorsub' => 'Keketatan seleksi. Tabel 2.a LKPS"',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],

            // START LAM-Teknik V1 2024
            [
                'id' => 38,
                'spmi_indikators_id' => 131,
                'kode' => 'A',
                'indikatorsub' => '[Sistem Tata Pamong] Kelengkapan struktur organisasi dan keefektifan penyelenggaraan organisasi',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'spmi_indikators_id' => 131,
                'kode' => 'B',
                'indikatorsub' => '[Sistem Tata Pamong] Perwujudan good governance dan pemenuhan lima pilar sistem tata pamong, yang mencakup: 1) Kredibel, 2) Transparan, 3) Akuntabel, 4) Bertanggung jawab, 5) Adil.	',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'spmi_indikators_id' => 132,
                'kode' => 'A',
                'indikatorsub' => '[Kepemimpinan dan Kemampuan Manajerial] Komitmen pimpinan UPPS.',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'spmi_indikators_id' => 132,
                'kode' => 'B',
                'indikatorsub' => '[Kepemimpinan dan Kemampuan Manajerial] Kapabilitas pimpinan UPPS, mencakup aspek: 1) perencanaan, 2) pengorganisasian, 3) penempatan personel, 4) pelaksanaan, 5) pengendalian dan pengawasan, dan 6) pelaporan yang menjadi dasar tindak lanjut. ',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'spmi_indikators_id' => 134,
                'kode' => 'A',
                'indikatorsub' => '[Kerjasama [Data]] Kerjasama perguruan tinggi di bidang pendidikan, penelitian dan PkM dalam 3 tahun terakhir.Tabel 1 LKPS ',
                'asal' => '',
                'rumus' => 'RK = ((a x N1) + (b x N2) + (c x N3)) / NDT',
                'keterangan' => 'N1 = Jumlah kerjasama pendidikan. | N2 = Jumlah kerjasama penelitian.	| N3 = Jumlah kerjasama pengabdian kepada masyarakat.	| NDTPS = Jumlah dosen tetap yang ditugaskan sebagai pengampu mata kuliah dengan bidang keahlian yang sesuai dengan kompetensi inti program studi yang diakreditasi.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'spmi_indikators_id' => 134,
                'kode' => 'B',
                'indikatorsub' => '[Kerjasama [Data]] B. Kerjasama tingkat internasional, nasional, wilayah/lokal yang relevan dengan program studi dan dikelola oleh UPPS dalam 3 tahun terakhir. Tabel 1 LKPS',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '4: NI ≥ a | 3-4: NI < a DAN NN ≥ b | 2-3: 0 < NI < a DAN 0 < NN < b | 2: NI = 0 DAN NN = 0 DAN NW ≥ c | 0-2: NI = 0 DAN NN = 0 DAN NW < c',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'spmi_indikators_id' => 137,
                'kode' => '0',
                'indikatorsub' => 'Pilih kelompok program studi berdasarkan jumlah kebutuhan lulusan sesuai pilihan yang tersedia. 1: Tinggi; 2: Rendah.',
                'asal' => '',
                'rumus' => 'Tidak Ada',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 0,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'spmi_indikators_id' => 137,
                'kode' => '1',
                'indikatorsub' => 'Untuk program studi dengan jumlah kebutuhan lulusan tinggi berlaku perhitungan Skor sebagai berikut:	',
                'asal' => '',
                'rumus' => 'Rasio = NA / NB',
                'keterangan' => 'NA = Jumlah calon mahasiswa yang ikut seleksi.	| NB = Jumlah calon mahasiswa yang lulus seleksi.	',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'spmi_indikators_id' => 137,
                'kode' => '1',
                'indikatorsub' => 'Untuk program studi dengan jumlah kebutuhan lulusan rendah berlaku pemberian Skor sesuai kondisi berikut:',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'spmi_indikators_id' => 138,
                'kode' => 'A',
                'indikatorsub' => 'Peningkatan animo calon mahasiswa. Tabel 2.a LKPS',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'spmi_indikators_id' => 138,
                'kode' => 'B',
                'indikatorsub' => 'Mahasiswa asing Tabel 2.b LKPS',
                'asal' => '',
                'rumus' => 'PMA = (NMAFT + NMAPT) / NMUPPS',
                'keterangan' => 'NMUPPS = Jumlah mahasiswa aktif di UPPS dalam 3 tahun terakhir (TS-2 s.d. TS).	| NMAFT = Jumlah mahasiswa asing penuh waktu dalam 3 tahun terakhir (TS-2 s.d. TS)	| NMAPT = Jumlah mahasiswa asing paruh waktu dalam 3 tahun terakhir (TS-2 s.d. TS)',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'spmi_indikators_id' => 139,
                'kode' => 'A',
                'indikatorsub' => 'A. Ketersediaan layanan kemahasiswaan di bidang',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '1) penalaran, minat dan bakat, 2) kesejahteraan (bimbingan dan konseling, layanan beasiswa, dan layanan kesehatan), dan 3) bimbingan karir dan kewirausahaan.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'spmi_indikators_id' => 139,
                'kode' => 'B',
                'indikatorsub' => 'B. Akses dan mutu layanan kemahasiswaan.	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'spmi_indikators_id' => 154,
                'kode' => 'A',
                'indikatorsub' => 'Kualifikasi dan kecukupan tenaga kependidikan berdasarkan jenis pekerjaannya (administrasi, pustakawan, teknisi, dll.)	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => 'Catatan: Penilaian kecukupan tidak hanya ditentukan oleh jumlah tenaga kependidikan, namun keberadaan dan pemanfaatan teknologi informasi dan komputer dalam proses administrasi dapat dijadikan pertimbangan untuk menilai efektifitas pekerjaan dan kebutuhan akan tenaga kependidikan.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'spmi_indikators_id' => 154,
                'kode' => 'B',
                'indikatorsub' => 'Kualifikasi dan kecukupan laboran untuk mendukung proses pembelajaran sesuai dengan kebutuhan program studi. Tabel 3.c) LKPS',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'spmi_indikators_id' => 161,
                'kode' => 'A',
                'indikatorsub' => 'Keterlibatan pemangku kepentingan dalam proses evaluasi dan pemutakhiran kurikulum.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'spmi_indikators_id' => 161,
                'kode' => 'B',
                'indikatorsub' => 'Kesesuaian capaian pembelajaran dengan profil lulusan dan jenjang KKNI/SKKNI.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'spmi_indikators_id' => 161,
                'kode' => 'C',
                'indikatorsub' => 'Ketepatan struktur kurikulum dalam pembentukan capaian pembelajaran.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'spmi_indikators_id' => 163,
                'kode' => 'A',
                'indikatorsub' => 'Ketersediaan dan kelengkapan dokumen rencana pembelajaran semester (RPS) ',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'spmi_indikators_id' => 163,
                'kode' => 'B',
                'indikatorsub' => 'Kedalaman dan keluasan RPS sesuai dengan capaian pembelajaran lulusan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'spmi_indikators_id' => 164,
                'kode' => 'A',
                'indikatorsub' => 'Bentuk interaksi antara dosen, mahasiswa dan sumber belajar',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'spmi_indikators_id' => 164,
                'kode' => 'B',
                'indikatorsub' => 'Pemantauan kesesuaian proses terhadap rencana pembelajaran',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'spmi_indikators_id' => 164,
                'kode' => 'C',
                'indikatorsub' => 'Proses pembelajaran yang terkait dengan penelitian harus mengacu SN Dikti Penelitian: 1) hasil penelitian: harus memenuhi pengembangan IPTEKS, meningkatkan kesejahteraan masyarakat, dan daya saing bangsa. 2) isi penelitian: memenuhi kedalaman dan keluasan materi penelitian sesuai capaian pembelajaran. 3) proses penelitian: mencakup perencanaan, pelaksanaan, dan pelaporan. 4) penilaian penelitian memenuhi unsur edukatif, obyektif, akuntabel, dan transparan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'spmi_indikators_id' => 164,
                'kode' => 'D',
                'indikatorsub' => 'Proses pembelajaran yang terkait dengan PkM harus mengacu SN Dikti PkM: 1) hasil PkM: harus memenuhi pengembangan IPTEKS, meningkatkan kesejahteraan masyarakat, dan daya saing bangsa. 2) isi PkM: memenuhi kedalaman dan keluasan materi PkM sesuai capaian pembelajaran. 3) proses PkM:  mencakup perencanaan, pelaksanaan, dan pelaporan. 4) penilaian PkM memenuhi unsur edukatif, obyektif, akuntabel, dan transparan',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 62,
                'spmi_indikators_id' => 164,
                'kode' => 'E',
                'indikatorsub' => 'Kesesuaian metode pembelajaran dengan capaian pembelajaran. Contoh: RBE (research based education), IBE (industry based education), teaching factory/teaching industry, dll.	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'spmi_indikators_id' => 167,
                'kode' => 'A',
                'indikatorsub' => 'Mutu pelaksanaan penilaian pembelajaran (proses dan hasil belajar mahasiswa) untuk mengukur ketercapaian capaian pembelajaran berdasarkan prinsip penilaian yang mencakup: 1) edukatif, 2) otentik, 3) objektif, 4) akuntabel, dan 5) transparan, yang dilakukan secara terintegrasi',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'spmi_indikators_id' => 167,
                'kode' => 'B',
                'indikatorsub' => 'Pelaksanaan penilaian terdiri atas teknik dan instrumen penilaian. Teknik penilaian terdiri dari: 1) observasi, 2) partisipasi, 3) unjuk kerja, 4) test tertulis, 5) test lisan, dan 6) angket. Instrumen penilaian terdiri dari: 1) penilaian proses dalam bentuk rubrik, dan/ atau; 2) penilaian hasil dalam bentuk portofolio, atau 3) karya disain."	',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'spmi_indikators_id' => 167,
                'kode' => 'C',
                'indikatorsub' => 'Pelaksanaan penilaian memuat unsur-unsur sebagai berikut: 1) mempunyai kontrak rencana penilaian, 2) melaksanakan penilaian sesuai kontrak atau kesepakatan, 3) memberikan umpan balik dan memberi kesempatan untuk mempertanyakan hasil kepada mahasiswa, 4) mempunyai dokumentasi penilaian proses dan hasil belajar mahasiswa, 5) mempunyai prosedur yang mencakup tahap perencanaan, kegiatan pemberian tugas atau soal, observasi kinerja, pengembalian hasil observasi, dan pemberian nilai akhir, 6) pelaporan penilaian berupa kualifikasi keberhasilan mahasiswa dalam menempuh suatu mata kuliah dalam bentuk huruf dan angka, 7) mempunyai bukti-bukti rencana dan telah melakukan proses perbaikan berdasar hasil monev penilaian.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'spmi_indikators_id' => 170,
                'kode' => 'A',
                'indikatorsub' => 'Tingkat kepuasan mahasiswa terhadap proses pendidikan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => 'Tabel 5.c LKPS Aspek yang diukur: 1) Keandalan (reliability): kemampuan dosen, tenaga kependidikan, dan pengelola dalam memberikan pelayanan; 2) Daya tanggap (responsiveness): kemauan dari dosen, tenaga kependidikan, dan pengelola dalam membantu mahasiswa dan memberikan jasa dengan cepat; 3) Kepastian (assurance): kemampuan dosen, tenaga kependidikan, dan pengelola untuk memberi keyakinan kepada mahasiswa bahwa pelayanan yang diberikan telah sesuai dengan ketentuan; 4) Empati (empathy): kesediaan/kepedulian dosen, tenaga kependidikan, dan pengelola untuk memberi perhatian kepada mahasiswa; dan 5) Tangible: penilaian mahasiswa terhadap kecukupan, aksesibitas, kualitas sarana dan prasarana.',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'spmi_indikators_id' => 170,
                'kode' => 'B',
                'indikatorsub' => 'Analisis dan tindak lanjut dari hasil pengukuran kepuasan mahasiswa.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 68,
                'spmi_indikators_id' => 205,
                'kode' => 'A',
                'indikatorsub' => 'Metoda rekrutmen dan sistem seleksi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 69,
                'spmi_indikators_id' => 205,
                'kode' => 'B',
                'indikatorsub' => 'Kriteria penerimaan mahasiswa.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 70,
                'spmi_indikators_id' => 205,
                'kode' => 'C',
                'indikatorsub' => 'Proses seleksi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'spmi_indikators_id' => 206,
                'kode' => 'A',
                'indikatorsub' => '"Ketersediaan layanan kemahasiswaan dalam bentuk: 1) bimbingan dan konseling, 2) layanan beasiswa, dan 3) layanan kesehatan."',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'spmi_indikators_id' => 206,
                'kode' => 'B',
                'indikatorsub' => 'Akses dan mutu layanan kemahasiswaan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 73,
                'spmi_indikators_id' => 210,
                'kode' => 'A',
                'indikatorsub' => 'Metode rekrutmen',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 74,
                'spmi_indikators_id' => 210,
                'kode' => 'B',
                'indikatorsub' => 'Keketatan seleksi',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // END LAM-Teknik V1 2024

            // START LAM-Teknik V2 2025
            [
                'id' => 75,
                'spmi_indikators_id' => 214,
                'kode' => 'I',
                'indikatorsub' => 'Kelengkapan struktur organisasi dan kebijakan operasional yang berpedoman pada statuta Perguruan Tinggi yang digunakan.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 76,
                'spmi_indikators_id' => 214,
                'kode' => 'II',
                'indikatorsub' => 'Perwujudan Good University Governance mengacu pada sistem tata kelola yang efektif, transparan, dan akuntabel. ',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 77,
                'spmi_indikators_id' => 215,
                'kode' => 'I',
                'indikatorsub' => 'Pimpinan UPPS memiliki komitmen pada: 
                    (1) Visi dan tujuan organisasi; 
                    (2) Integritas dan transparansi; 
                    (3) Pengembangan sumber daya.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 78,
                'spmi_indikators_id' => 215,
                'kode' => 'II',
                'indikatorsub' => 'Kemampuan manajerial pimpinan UPPS',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 79,
                'spmi_indikators_id' => 216,
                'kode' => 'I',
                'indikatorsub' => 'Relevansi kerja sama pendidikan, penelitian, dan PkM dengan visi UPPS serta visi keilmuan program studi.
                    Tabel 2.a LKPS
                    Tabel 4.a LKPS',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 80,
                'spmi_indikators_id' => 216,
                'kode' => 'II',
                'indikatorsub' => 'Kerja sama tingkat internasional, nasional, wilayah/lokal yang relevan dengan program studi dan dikelola oleh UPPS dalam 3 tahun terakhir.
                    Tabel 2.a LKPS',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 81,
                'spmi_indikators_id' => 223,
                'kode' => 'I',
                'indikatorsub' => 'Profil lulusan yang ditetapkan oleh Program Studi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 82,
                'spmi_indikators_id' => 223,
                'kode' => 'II',
                'indikatorsub' => 'Kesesuaian Profil lulusan dengan capaian pembelajaran (CPL)',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 83,
                'spmi_indikators_id' => 224,
                'kode' => 'I',
                'indikatorsub' => 'Kesesuaian CPL dengan standar kompetensi lulusan yang  mencakup: (1) Konsep  rekayasa terapan yang spesifik dengan disiplin ilmu terkait; (2) kemampuan teknis dan kemampuan beradaptasi dengan standar keteknikan dan Teknologi Baru; (3) Keterampilan komunikasi dan kemampuan kerja tim; (4) kepatuhan terhadap etika profesi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 84,
                'spmi_indikators_id' => 224,
                'kode' => 'II',
                'indikatorsub' => 'Proses tinjauan rutin CPL.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 85,
                'spmi_indikators_id' => 225,
                'kode' => 'I',
                'indikatorsub' => 'Metode rekrutmen dan sistem seleksi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 86,
                'spmi_indikators_id' => 225,
                'kode' => 'II',
                'indikatorsub' => 'Kriteria penerimaan mahasiswa.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 87,
                'spmi_indikators_id' => 225,
                'kode' => 'III',
                'indikatorsub' => 'Proses seleksi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 88,
                'spmi_indikators_id' => 226,
                'kode' => 'I',
                'indikatorsub' => 'Ketersediaan dan kelengkapan dokumen RPS yang terdiri dari:
                    1. Nama program studi, nama dan kode mata kuliah, semester, sks, nama dosen pengampu;
                    2. Capaian pembelajaran lulusan yang dibebankan pada capaian pembelajaran mata kuliah;
                    3. Kemampuan akhir yang direncanakan pada tiap tahap pembelajaran untuk memenuhi capaian pembelajaran lulusan;
                    4. Bahan kajian yang terkait dengan kemampuan yang akan dicapai;
                    5. Metode pembelajaran;
                    6. Waktu yang disediakan untuk mencapai kemampuan pada tiap tahap pembelajaran;
                    7. Pengalaman belajar mahasiswa yang diwujudkan dalam deskripsi tugas yang harus dikerjakan oleh mahasiswa selama satu semester;
                    8. Kriteria, indikator, dan bobot penilaian; dan
                    9. Daftar referensi yang digunakan. 

                    Tabel 3.a.1. LKPS.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 89,
                'spmi_indikators_id' => 226,
                'kode' => 'II',
                'indikatorsub' => 'Proses tinjauan rutin RPS.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 90,
                'spmi_indikators_id' => 227,
                'kode' => 'I',
                'indikatorsub' => 'Proses pembelajaran untuk memastikan efektivitas, kualitas, dan keberhasilan pencapaian CPL.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 91,
                'spmi_indikators_id' => 227,
                'kode' => 'II',
                'indikatorsub' => 'Tinjauan rutin proses pembelajaran.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 92,
                'spmi_indikators_id' => 232,
                'kode' => 'I',
                'indikatorsub' => 'Pengelolaan suasana akademik',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 93,
                'spmi_indikators_id' => 232,
                'kode' => 'II',
                'indikatorsub' => 'Integritas dan kebebasan ilmiah: Kebebasan akademik, mimbar akademik dan otonomi keilmuan',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 94,
                'spmi_indikators_id' => 254,
                'kode' => 'I',
                'indikatorsub' => ' Kecukupan dan mutu sarana dan prasarana untuk mendukung kegiatan akademik yang meliputi: 
                    (1) Ketersediaan media pembelajaran, perangkat elektronik, alat praktik laboratorium; 
                    (2) Ketersediaan ruang kelas, laboratorium sesuai dengan panduan asosiasi penyelenggara program studi, dan perpustakaan; 
                    (3) Kelayakan sarana dan prasarana; 
                    (4) Kemudahan akses sarana prasarana.

                    Tabel 5.a. LKPS.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 95,
                'spmi_indikators_id' => 254,
                'kode' => 'II',
                'indikatorsub' => 'Kecukupan dan mutu sarana dan prasarana untuk mendukung kegiatan non akademik yang meliputi: 
                    (1) Pusat kesehatan, pusat layanan konseling, pusat layanan karir, dan fasilitas ibadah; 
                    (2) Kelayakan sarana dan prasarana; dan
                    (3) Kemudahan akses sarana prasarana.

                    Tabel 5.a. LKPS.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 96,
                'spmi_indikators_id' => 259,
                'kode' => 'I',
                'indikatorsub' => 'Prestasi mahasiswa di bidang akademik dalam 5 tahun terakhir.
                    Tabel 6.c.1. LKPS
                    Tabel 6.a LKPS  ',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 97,
                'spmi_indikators_id' => 259,
                'kode' => 'II',
                'indikatorsub' => 'Prestasi mahasiswa di bidang non akademik dalam 5 tahun terakhir.
                    Tabel 6.c.2. LKPS.
                    Tabel 6.a LKPS.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 98,
                'spmi_indikators_id' => 273,
                'kode' => 'I',
                'indikatorsub' => 'Keberadaan unit penjaminan mutu UPPS dan komitmen pimpinan dengan keberadaan 4 aspek: 
                    (1) Dokumen legal pembentukan unsur pelaksana penjaminan mutu; 
                    (2) Dokumen legal bahwa auditor bersifat independen; 
                    (3) Dokumen pelaksanaan audit mutu internal; 
                    (4)Dokumen Rapat Tinjauan Manajemen (RTM).',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 99,
                'spmi_indikators_id' => 273,
                'kode' => 'II',
                'indikatorsub' => 'Ketersediaan perangkat SPMI yang minimal mencakup: 
                    1. Kebijakan SPMI; 
                    2. Pedoman penerapan siklus PPEPP standar pendidikan tinggi dalam SPMI; 
                    3. Standar dan/atau kriteria, norma, acuan mutu penyelenggaraan pendidikan dan pengelolaan perguruan tinggi; dan 
                    4. Tata cara pendokumentasian implementasi SPMI, serta sistem penjaminan mutu memiliki pengakuan mutu dari lembaga audit eksternal, lembaga akreditasi, dan lembaga sertifikasi.

                    Tabel 7.a. LKPS.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 100,
                'spmi_indikators_id' => 278,
                'kode' => 'I',
                'indikatorsub' => 'Analisis lingkungan eksternal dalam pengembangan UPPS dan Program Studi.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 101,
                'spmi_indikators_id' => 278,
                'kode' => 'II',
                'indikatorsub' => 'Ketepatan analisis SWOT yang mengacu pada lingkungan eksternal dan analisis SWOT setiap kriteria.',
                'asal' => '',
                'rumus' => '',
                'keterangan' => '',
                'status' => 1,
                'calculate' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // [
            //     'id' => 102,
            //     'spmi_indikators_id' => 289,
            //     'kode' => 'I',
            //     'indikatorsub' => 'Kelengkapan struktur organisasi dan kebijakan operasional yang berpedoman pada statuta Perguruan Tinggi yang digunakan.',
            //     'asal' => '',
            //     'rumus' => '',
            //     'keterangan' => '',
            //     'status' => 1,
            //     'calculate' => 1,
            //     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            // ],
            // [
            //     'id' => 103,
            //     'spmi_indikators_id' => 289,
            //     'kode' => 'II',
            //     'indikatorsub' => 'Perwujudan Good University Governance mengacu pada sistem tata kelola yang efektif, transparan, dan akuntabel. ',
            //     'asal' => '',
            //     'rumus' => '',
            //     'keterangan' => '',
            //     'status' => 1,
            //     'calculate' => 1,
            //     'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            // ],

            // END LAM-Teknik V2 2025
        ];

        Spmiindikatorsub::insert($data);
    }
}
