<?php

namespace Database\Seeders;

use App\Models\Spmielemen;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;


class SpmielemenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // START Lembaga BAN-PT
            [
                'id' => 2,
                'lembagas_id' => 1,
                'kode' => 'A',
                'tahun' => 2024,
                'kriteria' => '[Kondisi Eksternal]',
                'keterangan' => 'Penilaian difokuskan pada kemampuan UPPS dalam menganalisis aspekaspek dalam lingkungan makro dan lingkungan mikro yang relevan dan dapat mempengaruhi eksistensi dan pengembangan PS maupun UPPS, serta konsistensi informasi dengan hasil analisis evaluasi diri terhadap rencana pengembangan ke depan.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'lembagas_id' => 1,
                'kode' => 'B',
                'tahun' => 2024,
                'kriteria' => '[Profil Unit Pengelola Program Studi]',
                'keterangan' => 'Penilaian difokuskan pada kemampuan unit pengelola program studi dan program studi dalam menyajikan seluruh informasi secara ringkas, komprehensif, serta konsisten terhadap data dan informasi yang disampaikan pada masing-masing kriteria.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'lembagas_id' => 1,
                'kode' => 'C.1',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Visi, Misi, Tujuan dan Strategi',
                'keterangan' => 'Penilaian difokuskan pada kejelasan arah, komitmen dan konsistensi pengembangan program studi oleh unit pengelola program studi untuk mencapai kinerja dan mutu yang ditargetkan berdasarkan misi dan langkah-langkah program yang terencana, efektif, dan terarah dalam rangka pewujudan visi perguruan tinggi dan visi keilmuan program studi.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'lembagas_id' => 1,
                'kode' => 'C.2',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Tata Pamong, Tata Kelola, dan Kerjasama',
                'keterangan' => 'Penilaian difokuskan pada kinerja dan keefektifan kepemimpinan, tata pamong, sistem manajemen sumber daya, sistem penjaminan mutu, sistem komunikasi dan teknologi informasi, program dan kegiatan yang diarahkan pada perwujudan visi dan penuntasan misi yang bermutu, serta terbangun dan terselenggaranya kerjasama dan kemitraan strategis dalam penyelenggaraan pendidikan tinggi, baik akademik maupun non akademik secara berkelanjutan pada tataran nasional, regional, maupun internasional untuk meningkatkan daya saing program studi',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'lembagas_id' => 1,
                'kode' => 'C.3',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Mahasiswa',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'lembagas_id' => 1,
                'kode' => 'C.4',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Sumber Daya Manusia',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'lembagas_id' => 1,
                'kode' => 'C.5',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Keuangan, Sarana dan Prasarana',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'lembagas_id' => 1,
                'kode' => 'C.6',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Pendidikan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'lembagas_id' => 1,
                'kode' => 'C.7',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Penelitian',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'lembagas_id' => 1,
                'kode' => 'C.8',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Pengabdian kepada Masyarakat',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'lembagas_id' => 1,
                'kode' => 'C.9',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Luaran dan Capaian Tridharma',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'lembagas_id' => 1,
                'kode' => 'D.1',
                'tahun' => 2024,
                'kriteria' => '[Analisis dan Penetapan Program Pengembangan] Analisis dan Capaian Kinerja',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'lembagas_id' => 1,
                'kode' => 'D.2',
                'tahun' => 2024,
                'kriteria' => '[Analisis dan Penetapan Program Pengembangan] Analisis SWOT atau Analisis Lain yang Relevan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'lembagas_id' => 1,
                'kode' => 'D.3',
                'tahun' => 2024,
                'kriteria' => '[Analisis dan Penetapan Program Pengembangan] Program Pengembangan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'lembagas_id' => 1,
                'kode' => 'D.4',
                'tahun' => 2024,
                'kriteria' => '[Analisis dan Penetapan Program Pengembangan] Program Keberlanjutan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'lembagas_id' => 1,
                'kode' => 'LED',
                'tahun' => 2024,
                'kriteria' => '-',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'lembagas_id' => 1,
                'kode' => 'DK',
                'tahun' => 2024,
                'kriteria' => '-',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 99,
                'lembagas_id' => 1,
                'kode' => 'Data',
                'tahun' => 2024,
                'kriteria' => '[Data APS]',
                'keterangan' => 'Data APS 4.0',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // END Lembaga BAN-PT

            // START Lembaga LAM Teknik v1 2024
            [
                'id' => 19,
                'lembagas_id' => 7,
                'kode' => 'LT.A',
                'tahun' => 2024,
                'kriteria' => '[Kondisi Eksternal]',
                'keterangan' => 'Penilaian difokuskan pada kemampuan UPPS dalam menganalisis aspekaspek dalam lingkungan makro dan lingkungan mikro yang relevan dan dapat mempengaruhi eksistensi dan pengembangan PS maupun UPPS, serta konsistensi informasi dengan hasil analisis evaluasi diri terhadap rencana pengembangan ke depan.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'lembagas_id' => 7,
                'kode' => 'LT.B',
                'tahun' => 2024,
                'kriteria' => '[Profil Unit Pengelola Program Studi]',
                'keterangan' => 'Penilaian difokuskan pada kemampuan unit pengelola program studi dan program studi dalam menyajikan seluruh informasi secara ringkas, komprehensif, serta konsisten terhadap data dan informasi yang disampaikan pada masing-masing kriteria.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'lembagas_id' => 7,
                'kode' => 'LT.C.1',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Visi, Misi, Tujuan dan Strategi',
                'keterangan' => 'Penilaian difokuskan pada kejelasan arah, komitmen dan konsistensi pengembangan program studi oleh unit pengelola program studi untuk mencapai kinerja dan mutu yang ditargetkan berdasarkan misi dan langkah-langkah program yang terencana, efektif, dan terarah dalam rangka pewujudan visi perguruan tinggi dan visi keilmuan program studi.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'lembagas_id' => 7,
                'kode' => 'LT.C.2',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Tata Pamong, Tata Kelola, dan Kerjasama',
                'keterangan' => 'Penilaian difokuskan pada kinerja dan keefektifan kepemimpinan, tata pamong, sistem manajemen sumber daya, sistem penjaminan mutu, sistem komunikasi dan teknologi informasi, program dan kegiatan yang diarahkan pada perwujudan visi dan penuntasan misi yang bermutu, serta terbangun dan terselenggaranya kerjasama dan kemitraan strategis dalam penyelenggaraan pendidikan tinggi, baik akademik maupun non akademik secara berkelanjutan pada tataran nasional, regional, maupun internasional untuk meningkatkan daya saing program studi',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'lembagas_id' => 7,
                'kode' => 'LT.C.3',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Mahasiswa',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'lembagas_id' => 7,
                'kode' => 'LT.C.4',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Sumber Daya Manusia',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'lembagas_id' => 7,
                'kode' => 'LT.C.5',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Keuangan, Sarana dan Prasarana',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'lembagas_id' => 7,
                'kode' => 'LT.C.6',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Pendidikan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'lembagas_id' => 7,
                'kode' => 'LT.C.7',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Penelitian',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'lembagas_id' => 7,
                'kode' => 'LT.C.8',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Pengabdian kepada Masyarakat',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'lembagas_id' => 7,
                'kode' => 'LT.C.9',
                'tahun' => 2024,
                'kriteria' => '[Kriteria] Luaran dan Capaian Tridharma',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'lembagas_id' => 7,
                'kode' => 'LT.D.1',
                'tahun' => 2024,
                'kriteria' => '[Penjaminan Mutu] Keberadaan unit peminjaman dan komitmen pimpinan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'lembagas_id' => 7,
                'kode' => 'LT.D.2',
                'tahun' => 2024,
                'kriteria' => '[Penjaminan Mutu] Ketersediaan dokumen dan pengakuan mutu eksternal',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'lembagas_id' => 7,
                'kode' => 'LT.D.3',
                'tahun' => 2024,
                'kriteria' => '[Penjaminan Mutu] Keterlaksanaan Penjaminan Mutu dan Audit Mutu Internal',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'lembagas_id' => 7,
                'kode' => 'LT.D.4',
                'tahun' => 2024,
                'kriteria' => '[Penjaminan Mutu] Kepuasan Pemangku Kepentingan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'lembagas_id' => 7,
                'kode' => 'LT.E.1',
                'tahun' => 2024,
                'kriteria' => '[Program Pengembangan Berkelanjutan] Analisis SWOT',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'lembagas_id' => 7,
                'kode' => 'LT.E.2',
                'tahun' => 2024,
                'kriteria' => '[Program Pengembangan Berkelanjutan] Tujuan Strategi Pengembangan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'lembagas_id' => 7,
                'kode' => 'LT.E.3',
                'tahun' => 2024,
                'kriteria' => '[Program Pengembangan Berkelanjutan] Program Pengembangan Berkelanjutan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // END Lembaga LAM Teknik v1 2024

            // START Lembaga LAM Teknik v2 2025
            [
                'id' => 37,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.1',
                'tahun' => 2025,
                'kriteria' => 'Kekhasan VMTS',
                'keterangan' => '-.',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.2',
                'tahun' => 2025,
                'kriteria' => 'Mekanisme penyusunan VMTS',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.3',
                'tahun' => 2025,
                'kriteria' => 'Tingkat pemahaman dan pencapaian VMTS',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.4',
                'tahun' => 2025,
                'kriteria' => 'Sistem Tata Pamong',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.5',
                'tahun' => 2025,
                'kriteria' => 'Komitmen pimpinan dan kemampuan manajerial',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 42,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.6',
                'tahun' => 2025,
                'kriteria' => 'Kerja sama',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.7',
                'tahun' => 2025,
                'kriteria' => 'Pelaksanaan kerja sama',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.8',
                'tahun' => 2025,
                'kriteria' => 'Pengelolaan keuangan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.9',
                'tahun' => 2025,
                'kriteria' => 'Biaya operasional, dana penelitian dan PkM',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.10',
                'tahun' => 2025,
                'kriteria' => 'Pemutakhiran kurikulum',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.11',
                'tahun' => 2025,
                'kriteria' => 'Profil lulusan dan CPL.',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.12',
                'tahun' => 2025,
                'kriteria' => 'Kesesuaian dan tinjauan CPL',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.13',
                'tahun' => 2025,
                'kriteria' => 'Kualitas Input Mahasiswa',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.14',
                'tahun' => 2025,
                'kriteria' => 'Rencana Proses Pembelajaran (RPS)',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.15',
                'tahun' => 2025,
                'kriteria' => 'Proses Pembelajaran (PS)',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 52,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.16',
                'tahun' => 2025,
                'kriteria' => 'Integrasi Penelitian dan PkM dalam pembelajaran.',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.17',
                'tahun' => 2025,
                'kriteria' => 'Basic sciences dan matematika',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.18',
                'tahun' => 2025,
                'kriteria' => 'Proyek rekayasa penciri bidang prodi (Capstone design)',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.19',
                'tahun' => 2025,
                'kriteria' => 'Suasana Akademik',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.20',
                'tahun' => 2025,
                'kriteria' => 'Penelitian',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.21',
                'tahun' => 2025,
                'kriteria' => 'Pkm',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.22',
                'tahun' => 2025,
                'kriteria' => 'Profil Dosen',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.23',
                'tahun' => 2025,
                'kriteria' => 'Tenaga Kependidikan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.24',
                'tahun' => 2025,
                'kriteria' => 'Beban kerja DTPS',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.25',
                'tahun' => 2025,
                'kriteria' => 'Kinerja DTPS',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 62,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.26',
                'tahun' => 2025,
                'kriteria' => 'Sarana dan Prasarana',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.27',
                'tahun' => 2025,
                'kriteria' => 'Keselamatan Kesehatan Kerja dan Lingkungan (K3L)',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.28',
                'tahun' => 2025,
                'kriteria' => 'Mahasiswa Asing',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.29',
                'tahun' => 2025,
                'kriteria' => 'Prestasi akademik dan nonakademik mahasiswa',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.30',
                'tahun' => 2025,
                'kriteria' => 'Prestasi akademik mahasiswa',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.31',
                'tahun' => 2025,
                'kriteria' => 'Masa studi',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 68,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.32',
                'tahun' => 2025,
                'kriteria' => 'Persentase Kelulusan tepat waktu',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 69,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.33',
                'tahun' => 2025,
                'kriteria' => 'Publikasi ilmiah mahasiswa',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 70,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.34',
                'tahun' => 2025,
                'kriteria' => 'Tracer Study',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.35',
                'tahun' => 2025,
                'kriteria' => 'Waktu Tunggu',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.36',
                'tahun' => 2025,
                'kriteria' => 'Tingkat dan ukuran tempat kerja lulusan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 73,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.37',
                'tahun' => 2025,
                'kriteria' => 'Keberadaan unit penjaminan mutu dan komitmen pimpinan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 74,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.38',
                'tahun' => 2025,
                'kriteria' => 'Indikator Kinerja Tambahan (IKT)',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 75,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.39',
                'tahun' => 2025,
                'kriteria' => 'Keterlaksanaan Penjaminan Mutu dan Audit Mutu Internal',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 76,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.40',
                'tahun' => 2025,
                'kriteria' => 'Evaluasi Capaian Kinerja',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 77,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.41',
                'tahun' => 2025,
                'kriteria' => 'Kepuasan Pemangku Kepentingan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 78,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.42',
                'tahun' => 2025,
                'kriteria' => 'Analisis Lingkungan Eksternal dalam Pengembangan UPPS dan Prodi serta analisis SWOT',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 79,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.43',
                'tahun' => 2025,
                'kriteria' => 'Tujuan Strategis Pengembangan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 80,
                'lembagas_id' => 10,
                'kode' => 'LT.V2.44',
                'tahun' => 2025,
                'kriteria' => 'Program Pengembangan Berkelanjutan',
                'keterangan' => '-',
                'status' => 1,
                'spmi_periodes_id' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // END Lembaga LAM Teknik v2 2025

        ];

        Spmielemen::insert($data);
    }
}
