<?php

namespace Database\Seeders;

use App\Models\Userprogramstudi;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserprogramstudiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'users_id' => 1,
                'programstudis_id' => 49,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'users_id' => 1,
                'programstudis_id' => 112,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'users_id' => 14,
                'programstudis_id' => 54,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'users_id' => 15,
                'programstudis_id' => 24,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],

            ['id' => 3, 'users_id' => 13, 'programstudis_id' => 51, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 6, 'users_id' => 9, 'programstudis_id' => 52, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 7, 'users_id' => 23, 'programstudis_id' => 1, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 8, 'users_id' => 24, 'programstudis_id' => 2, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 9, 'users_id' => 25, 'programstudis_id' => 3, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 10, 'users_id' => 26, 'programstudis_id' => 4, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 11, 'users_id' => 27, 'programstudis_id' => 5, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 12, 'users_id' => 28, 'programstudis_id' => 6, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 13, 'users_id' => 29, 'programstudis_id' => 7, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 14, 'users_id' => 30, 'programstudis_id' => 8, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 15, 'users_id' => 31, 'programstudis_id' => 9, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 16, 'users_id' => 32, 'programstudis_id' => 10, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 17, 'users_id' => 33, 'programstudis_id' => 11, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 18, 'users_id' => 34, 'programstudis_id' => 12, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 19, 'users_id' => 35, 'programstudis_id' => 13, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 20, 'users_id' => 36, 'programstudis_id' => 14, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 21, 'users_id' => 37, 'programstudis_id' => 15, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 22, 'users_id' => 38, 'programstudis_id' => 16, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 23, 'users_id' => 39, 'programstudis_id' => 17, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 24, 'users_id' => 40, 'programstudis_id' => 18, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 25, 'users_id' => 41, 'programstudis_id' => 19, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 26, 'users_id' => 42, 'programstudis_id' => 20, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 27, 'users_id' => 43, 'programstudis_id' => 21, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 28, 'users_id' => 44, 'programstudis_id' => 22, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 29, 'users_id' => 45, 'programstudis_id' => 23, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 30, 'users_id' => 15, 'programstudis_id' => 24, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 31, 'users_id' => 46, 'programstudis_id' => 25, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 32, 'users_id' => 47, 'programstudis_id' => 26, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 33, 'users_id' => 48, 'programstudis_id' => 27, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 34, 'users_id' => 49, 'programstudis_id' => 28, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 35, 'users_id' => 50, 'programstudis_id' => 29, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 36, 'users_id' => 51, 'programstudis_id' => 30, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 37, 'users_id' => 52, 'programstudis_id' => 31, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 38, 'users_id' => 53, 'programstudis_id' => 32, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 39, 'users_id' => 54, 'programstudis_id' => 33, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 40, 'users_id' => 55, 'programstudis_id' => 34, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 41, 'users_id' => 56, 'programstudis_id' => 35, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 42, 'users_id' => 57, 'programstudis_id' => 36, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 43, 'users_id' => 58, 'programstudis_id' => 37, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 44, 'users_id' => 59, 'programstudis_id' => 38, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 45, 'users_id' => 60, 'programstudis_id' => 39, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 46, 'users_id' => 61, 'programstudis_id' => 40, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 47, 'users_id' => 62, 'programstudis_id' => 41, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 48, 'users_id' => 63, 'programstudis_id' => 42, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 49, 'users_id' => 64, 'programstudis_id' => 43, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 50, 'users_id' => 65, 'programstudis_id' => 44, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 51, 'users_id' => 66, 'programstudis_id' => 45, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 52, 'users_id' => 16, 'programstudis_id' => 46, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 53, 'users_id' => 17, 'programstudis_id' => 47, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 54, 'users_id' => 18, 'programstudis_id' => 48, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 55, 'users_id' => 19, 'programstudis_id' => 49, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 56, 'users_id' => 20, 'programstudis_id' => 50, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 57, 'users_id' => 21, 'programstudis_id' => 53, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 58, 'users_id' => 14, 'programstudis_id' => 54, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 59, 'users_id' => 22, 'programstudis_id' => 55, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 60, 'users_id' => 67, 'programstudis_id' => 56, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 61, 'users_id' => 68, 'programstudis_id' => 57, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 62, 'users_id' => 69, 'programstudis_id' => 58, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 63, 'users_id' => 70, 'programstudis_id' => 59, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 64, 'users_id' => 70, 'programstudis_id' => 60, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 65, 'users_id' => 71, 'programstudis_id' => 61, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 66, 'users_id' => 72, 'programstudis_id' => 62, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 67, 'users_id' => 73, 'programstudis_id' => 63, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 68, 'users_id' => 74, 'programstudis_id' => 64, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 69, 'users_id' => 75, 'programstudis_id' => 65, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 70, 'users_id' => 76, 'programstudis_id' => 66, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 71, 'users_id' => 76, 'programstudis_id' => 67, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 72, 'users_id' => 77, 'programstudis_id' => 68, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 73, 'users_id' => 78, 'programstudis_id' => 69, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 74, 'users_id' => 79, 'programstudis_id' => 70, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 75, 'users_id' => 80, 'programstudis_id' => 71, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 76, 'users_id' => 81, 'programstudis_id' => 72, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 77, 'users_id' => 82, 'programstudis_id' => 79, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 78, 'users_id' => 83, 'programstudis_id' => 80, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 79, 'users_id' => 84, 'programstudis_id' => 81, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 80, 'users_id' => 85, 'programstudis_id' => 82, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 81, 'users_id' => 86, 'programstudis_id' => 83, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 82, 'users_id' => 87, 'programstudis_id' => 84, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 83, 'users_id' => 88, 'programstudis_id' => 85, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 84, 'users_id' => 89, 'programstudis_id' => 86, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 85, 'users_id' => 90, 'programstudis_id' => 87, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 86, 'users_id' => 91, 'programstudis_id' => 88, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 87, 'users_id' => 92, 'programstudis_id' => 89, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 88, 'users_id' => 93, 'programstudis_id' => 90, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 89, 'users_id' => 94, 'programstudis_id' => 91, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 90, 'users_id' => 95, 'programstudis_id' => 92, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 91, 'users_id' => 96, 'programstudis_id' => 93, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 92, 'users_id' => 97, 'programstudis_id' => 94, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 93, 'users_id' => 98, 'programstudis_id' => 95, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 94, 'users_id' => 99, 'programstudis_id' => 96, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 95, 'users_id' => 100, 'programstudis_id' => 97, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 96, 'users_id' => 101, 'programstudis_id' => 98, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 97, 'users_id' => 102, 'programstudis_id' => 99, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 98, 'users_id' => 103, 'programstudis_id' => 100, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 99, 'users_id' => 104, 'programstudis_id' => 101, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 100, 'users_id' => 105, 'programstudis_id' => 102, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 101, 'users_id' => 106, 'programstudis_id' => 103, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 102, 'users_id' => 107, 'programstudis_id' => 104, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 103, 'users_id' => 108, 'programstudis_id' => 105, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 104, 'users_id' => 109, 'programstudis_id' => 106, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 105, 'users_id' => 110, 'programstudis_id' => 107, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 106, 'users_id' => 111, 'programstudis_id' => 108, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 107, 'users_id' => 112, 'programstudis_id' => 109, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 108, 'users_id' => 113, 'programstudis_id' => 110, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 109, 'users_id' => 114, 'programstudis_id' => 111, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 110, 'users_id' => 115, 'programstudis_id' => 112, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 111, 'users_id' => 116, 'programstudis_id' => 113, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 112, 'users_id' => 117, 'programstudis_id' => 114, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 113, 'users_id' => 118, 'programstudis_id' => 115, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 114, 'users_id' => 119, 'programstudis_id' => 116, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 115, 'users_id' => 120, 'programstudis_id' => 117, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 116, 'users_id' => 121, 'programstudis_id' => 118, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 117, 'users_id' => 122, 'programstudis_id' => 119, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 118, 'users_id' => 123, 'programstudis_id' => 120, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 119, 'users_id' => 124, 'programstudis_id' => 121, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 120, 'users_id' => 125, 'programstudis_id' => 122, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 121, 'users_id' => 126, 'programstudis_id' => 123, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 122, 'users_id' => 127, 'programstudis_id' => 124, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 123, 'users_id' => 128, 'programstudis_id' => 125, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 124, 'users_id' => 129, 'programstudis_id' => 126, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 125, 'users_id' => 130, 'programstudis_id' => 127, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 126, 'users_id' => 131, 'programstudis_id' => 128, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 127, 'users_id' => 132, 'programstudis_id' => 129, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 128, 'users_id' => 133, 'programstudis_id' => 130, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 129, 'users_id' => 134, 'programstudis_id' => 131, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 130, 'users_id' => 135, 'programstudis_id' => 132, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 131, 'users_id' => 136, 'programstudis_id' => 133, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 132, 'users_id' => 137, 'programstudis_id' => 134, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => 133, 'users_id' => 138, 'programstudis_id' => 135, 'status' => 1, 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            [
                'id' => 151,
                'users_id' => 13,
                'programstudis_id' => 65,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 152,
                'users_id' => 13,
                'programstudis_id' => 125,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 153,
                'users_id' => 13,
                'programstudis_id' => 79,
                'status' => 1,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],

        ];

        Userprogramstudi::insert($data);
    }
}
