<?php

namespace Database\Seeders;

use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 9 - 68 = S1 (kecuali 10 - 12)
        // 69 - 81 = D4
        // 82 - 120 = S2
        // 121 - xxx = S3

        $data = [
            [
                'id' => 1,
                'name' => 'Super Admin',
                'username' => 'supadminiqas',
                'email' => 'superadminiqas@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'name' => 'Admin',
                'username' => 'adminiqas',
                'email' => 'adminiqas@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'name' => 'Pimpinan LP2MP',
                'username' => 'pim_lp2mp',
                'email' => 'pimpinanlp2mpiqas@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'name' => 'Pimpinan Universitas',
                'username' => 'pim_univ',
                'email' => 'pimuniv@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'name' => 'Kapus Penjamu internal',
                'username' => 'penjamu_lp2mp',
                'email' => 'penjamulp2mp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'name' => 'Kapus Penjamu Eksternal',
                'username' => 'penjamu_lp2mp2',
                'email' => 'penjamulp2mp2@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'name' => 'Pimpinan Fakultas Teknik',
                'username' => 'pim_ft',
                'email' => 'pimft@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'name' => 'TPMF Fakultas Hukum',
                'username' => 'tpmf_hukum',
                'email' => 'tpmf_hukum@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'name' => 'Kepala Departemen',
                'username' => 'kadep_elektro',
                'email' => 'kadepelektro@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'name' => 'GPM Elektro',
                'username' => 'gpm_elektro',
                'email' => 'gpm_elektro@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'name' => 'Auditor',
                'username' => 'auditor_tes',
                'email' => 'auditortes@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],

            // Start Kaprodi Fakultas Teknik
            [
                'id' => 9,
                'name' => 'Kaprodi S1 Teknik Lingkungan',
                'username' => 'kaprodi_lingkungan',
                'email' => 'kaprodi_lingkungan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'name' => 'Kaprodi S1 Teknik Komputer',
                'username' => 'kaprodi_tekom',
                'email' => 'kaprodi_tekom@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'name' => 'Kaprodi S1 Teknik Perkapalan',
                'username' => 'kaprodi_perkapalan',
                'email' => 'kaprodi_perkapalan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'name' => 'Kaprodi S1 Teknik Elektro',
                'username' => 'kaprodi_elektro',
                'email' => 'kaprodi_elektro@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'name' => 'Kaprodi S1 Teknik Geodesi',
                'username' => 'kaprodi_geodesi',
                'email' => 'kaprodi_geodesi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'name' => 'Kaprodi S1 Teknik Geologi',
                'username' => 'kaprodi_geologi',
                'email' => 'kaprodi_geologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'name' => 'Kaprodi S1 Teknik Industri',
                'username' => 'kaprodi_industri',
                'email' => 'kaprodi_industri@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'name' => 'Kaprodi S1 Teknik Kimia',
                'username' => 'kaprodi_tekim',
                'email' => 'kaprodi_tekim@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'name' => 'Kaprodi S1 Teknik Mesin',
                'username' => 'kaprodi_mesin',
                'email' => 'kaprodi_mesin@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'name' => 'Kaprodi S1 Teknik Sipil',
                'username' => 'kaprodi_sipil',
                'email' => 'kaprodi_sipil@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'name' => 'Kaprodi S1 Arsitektur',
                'username' => 'kaprodi_arsitektur',
                'email' => 'kaprodi_arsitektur@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 59,
                'name' => 'Kaprodi S1 Teknik Perencanaan Wilayah dan Kota',
                'username' => 'kaprodi_pwk',
                'email' => 'kaprodi_pwk@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 86,
                'name' => 'Kaprodi S2 Arsitektur',
                'username' => 'kaprodi_s2arsitektur',
                'email' => 'kaprodi_s2arsitektur@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 108,
                'name' => 'Kaprodi S2 Teknik Perencanaan Wilayah dan Kota',
                'username' => 'kaprodi_s2pwk',
                'email' => 'kaprodi_s2pwk@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 115,
                'name' => 'Kaprodi S2 Teknik dan Manajemen Industri',
                'username' => 'kaprodi_s2industri',
                'email' => 'kaprodi_s2industri@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 116,
                'name' => 'Kaprodi S2 Teknik Elektro',
                'username' => 'kaprodi_s2elektro',
                'email' => 'kaprodi_s2elektro@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 117,
                'name' => 'Kaprodi S2 Teknik Kimia',
                'username' => 'kaprodi_s2tekim',
                'email' => 'kaprodi_s2tekim@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 118,
                'name' => 'Kaprodi S2 Teknik Lingkungan',
                'username' => 'kaprodi_s2lingkungan',
                'email' => 'kaprodi_s2lingkungan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 119,
                'name' => 'Kaprodi S2 Teknik Mesin',
                'username' => 'kaprodi_s2mesin',
                'email' => 'kaprodi_s2mesin@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 120,
                'name' => 'Kaprodi S2 Teknik Sipil',
                'username' => 'kaprodi_s2sipil',
                'email' => 'kaprodi_s2sipil@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 124,
                'name' => 'Kaprodi S3 Ilmu Arsitektur dan Perkotaan',
                'username' => 'kaprodi_s3dtap',
                'email' => 'kaprodi_s3dtap@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 129,
                'name' => 'Kaprodi S3 Ilmu Teknik Sipil',
                'username' => 'kaprodi_s3sipil',
                'email' => 'kaprodi_s3sipil@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 132,
                'name' => 'Kaprodi S3 Teknik Perencanaan Wilayah dan Kota',
                'username' => 'kaprodi_s3pwk',
                'email' => 'kaprodi_s3pwk@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 137,
                'name' => 'Kaprodi S3 Teknik Kimia',
                'username' => 'kaprodi_s3tekim',
                'email' => 'kaprodi_s3tekim@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 138,
                'name' => 'Kaprodi S3 Teknik Mesin',
                'username' => 'kaprodi_s3mesin',
                'email' => 'kaprodi_s3mesin@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi Fakultas Teknik

            // Start Kaprodi FISIP
            [
                'id' => 15,
                'name' => 'Kaprodi S1 Ilmu Pemerintahan',
                'username' => 'kaprodi_pemerintahan',
                'email' => 'kaprodi_pemerintahan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'name' => 'Kaprodi S1 Administrasi Bisnis',
                'username' => 'kaprodi_adminbisnis',
                'email' => 'kaprodi_adminbisnis@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'name' => 'Kaprodi S1 Administrasi Publik',
                'username' => 'kaprodi_adminpublik',
                'email' => 'kaprodi_adminpublik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'name' => 'Kaprodi S1 Administrasi Publik K. Rembang',
                'username' => 'kaprodi_adminpublik_rembang',
                'email' => 'kaprodi_adminpublik_rembang@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 41,
                'name' => 'Kaprodi S1 Hubungan Internasional',
                'username' => 'kaprodi_hubinter',
                'email' => 'kaprodi_hubinter@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 45,
                'name' => 'Kaprodi S1 Ilmu Komunikasi',
                'username' => 'kaprodi_komunikasi',
                'email' => 'kaprodi_komunikasi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 82,
                'name' => 'Kaprodi S2 Administrasi Bisnis',
                'username' => 'kaprodi_s2adminbisnis',
                'email' => 'kaprodi_s2adminbisnis@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 83,
                'name' => 'Kaprodi S2 Administrasi Publik',
                'username' => 'kaprodi_s2adminpublik',
                'email' => 'kaprodi_s2adminpublik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 96,
                'name' => 'Kaprodi S2 Ilmu Komunikasi',
                'username' => 'kaprodi_s2komunikasi',
                'email' => 'kaprodi_s2komunikasi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 99,
                'name' => 'Kaprodi S2 Ilmu Politik',
                'username' => 'kaprodi_s2politik',
                'email' => 'kaprodi_s2politik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 121,
                'name' => 'Kaprodi S3 Administrasi Publik',
                'username' => 'kaprodi_s3adminpublik',
                'email' => 'kaprodi_s3adminpublik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 128,
                'name' => 'Kaprodi S3 Ilmu Sosial',
                'username' => 'kaprodi_s3sosial',
                'email' => 'kaprodi_s3sosial@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FISIP

            // Start Kaprodi FPP
            [
                'id' => 26,
                'name' => 'Kaprodi S1 Agribisnis',
                'username' => 'kaprodi_agribisnis',
                'email' => 'kaprodi_agribisnis@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'name' => 'Kaprodi S1 Agroekoteknologi',
                'username' => 'kaprodi_agroekoteknologi',
                'email' => 'kaprodi_agroekoteknologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 61,
                'name' => 'Kaprodi S1 Peternakan',
                'username' => 'kaprodi_peternakan',
                'email' => 'kaprodi_peternakan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 68,
                'name' => 'Kaprodi S1 Teknologi Pangan',
                'username' => 'kaprodi_teknologipangan',
                'email' => 'kaprodi_teknologipangan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 84,
                'name' => 'Kaprodi S2 Agribisnis',
                'username' => 'kaprodi_s2agribisnis',
                'email' => 'kaprodi_s2agribisnis@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 109,
                'name' => 'Kaprodi S2 Peternakan',
                'username' => 'kaprodi_s2peternakan',
                'email' => 'kaprodi_s2peternakan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 133,
                'name' => 'Kaprodi S3 Peternakan',
                'username' => 'kaprodi_s3peternakan',
                'email' => 'kaprodi_s3peternakan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FPP

            //Start Kaprodi FPIK
            [
                'id' => 28,
                'name' => 'Kaprodi S1 Akuakultur',
                'username' => 'kaprodi_akuakultur',
                'email' => 'kaprodi_akuakultur@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 44,
                'name' => 'Kaprodi S1 Ilmu Kelautan',
                'username' => 'kaprodi_kelautan',
                'email' => 'kaprodi_kelautan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 56,
                'name' => 'Kaprodi S1 Manajemen Sumber Daya Perairan',
                'username' => 'kaprodi_akuatik',
                'email' => 'kaprodi_akuatik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 58,
                'name' => 'Kaprodi S1 Oseanografi',
                'username' => 'kaprodi_oseanografi',
                'email' => 'kaprodi_oseanografi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 60,
                'name' => 'Kaprodi S1 Perikanan Tangkap',
                'username' => 'kaprodi_perikanantangkap',
                'email' => 'kaprodi_perikanantangkap@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 67,
                'name' => 'Kaprodi S1 Teknologi Hasil Perikanan',
                'username' => 'kaprodi_thp',
                'email' => 'kaprodi_thp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 95,
                'name' => 'Kaprodi S2 Ilmu Kelautan',
                'username' => 'kaprodi_s2kelautan',
                'email' => 'kaprodi_s2kelautan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 106,
                'name' => 'Kaprodi S2 Manajemen Sumber Daya Perairan',
                'username' => 'kaprodi_s2akuatik',
                'email' => 'kaprodi_s2akuatik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 126,
                'name' => 'Kaprodi S3 Ilmu Kelautan',
                'username' => 'kaprodi_s3kelautan',
                'email' => 'kaprodi_s3kelautan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 131,
                'name' => 'Kaprodi S3 Manajemen Sumber Daya Perairan',
                'username' => 'kaprodi_s3akuatik',
                'email' => 'kaprodi_s3akuatik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FPIK

            // Start Kaprodi FEB
            [
                'id' => 29,
                'name' => 'Kaprodi S1 Akuntansi',
                'username' => 'kaprodi_akuntansi',
                'email' => 'kaprodi_akuntansi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'name' => 'Kaprodi S1 Bisnis Digital',
                'username' => 'kaprodi_bisnisdigital',
                'email' => 'kaprodi_bisnisdigital@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'name' => 'Kaprodi S1 Ekonomi',
                'username' => 'kaprodi_ekonomi',
                'email' => 'kaprodi_ekonomi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'name' => 'Kaprodi S1 Ekonomi Islam',
                'username' => 'kaprodi_ekis',
                'email' => 'kaprodi_ekis@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 55,
                'name' => 'Kaprodi S1 Manajemen',
                'username' => 'kaprodi_manajemen',
                'email' => 'kaprodi_manajemen@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 85,
                'name' => 'Kaprodi S2 Akuntansi',
                'username' => 'kaprodi_s2akuntansi',
                'email' => 'kaprodi_s2akuntansi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 88,
                'name' => 'Kaprodi S2 Ekonomi',
                'username' => 'kaprodi_s2ekonomi',
                'email' => 'kaprodi_s2ekonomi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 105,
                'name' => 'Kaprodi S2 Manajemen',
                'username' => 'kaprodi_s2manajemen',
                'email' => 'kaprodi_s2manajemen@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 122,
                'name' => 'Kaprodi S3 Ekonomi',
                'username' => 'kaprodi_s3ekonomi',
                'email' => 'kaprodi_s3ekonomi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FEB

            // Start Kaprodi FIB
            [
                'id' => 30,
                'name' => 'Kaprodi S1 Antropologi Sosial',
                'username' => 'kaprodi_antropologi',
                'email' => 'kaprodi_antropologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'name' => 'Kaprodi S1 Bahasa dan Kebudayaan Jepang',
                'username' => 'kaprodi_bahasajepang',
                'email' => 'kaprodi_bahasajepang@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 46,
                'name' => 'Kaprodi S1 Ilmu Perpustakaan',
                'username' => 'kaprodi_ilpus',
                'email' => 'kaprodi_ilpus@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 63,
                'name' => 'Kaprodi S1 Sastra Indonesia',
                'username' => 'kaprodi_sastraindonesia',
                'email' => 'kaprodi_sastraindonesia@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 64,
                'name' => 'Kaprodi S1 Sastra Inggris',
                'username' => 'kaprodi_sastrainggris',
                'email' => 'kaprodi_sastrainggris@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 65,
                'name' => 'Kaprodi S1 Sejarah',
                'username' => 'kaprodi_sejarah',
                'email' => 'kaprodi_sejarah@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 98,
                'name' => 'Kaprodi S2 Ilmu Linguistik',
                'username' => 'kaprodi_s2linguistik',
                'email' => 'kaprodi_s2linguistik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 112,
                'name' => 'Kaprodi S2 Sejarah',
                'username' => 'kaprodi_s2sejarah',
                'email' => 'kaprodi_s2sejarah@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 114,
                'name' => 'Kaprodi S2 Susastra',
                'username' => 'kaprodi_s2susastra',
                'email' => 'kaprodi_s2susastra@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 135,
                'name' => 'Kaprodi S3 Sejarah',
                'username' => 'kaprodi_s3sejarah',
                'email' => 'kaprodi_s3sejarah@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FIB

            // Start Kaprodi FSM
            [
                'id' => 33,
                'name' => 'Kaprodi S1 Biologi',
                'username' => 'kaprodi_biologi',
                'email' => 'kaprodi_biologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'name' => 'Kaprodi S1 Bioteknologi',
                'username' => 'kaprodi_biotek',
                'email' => 'kaprodi_biotek@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'name' => 'Kaprodi S1 Fisika',
                'username' => 'kaprodi_fisika',
                'email' => 'kaprodi_fisika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 47,
                'name' => 'Kaprodi S1 Informatika',
                'username' => 'kaprodi_informatika',
                'email' => 'kaprodi_informatika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 54,
                'name' => 'Kaprodi S1 Kimia',
                'username' => 'kaprodi_kimia',
                'email' => 'kaprodi_kimia@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 57,
                'name' => 'Kaprodi S1 Matematika',
                'username' => 'kaprodi_matematika',
                'email' => 'kaprodi_matematika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 66,
                'name' => 'Kaprodi S1 Statistika',
                'username' => 'kaprodi_statistika',
                'email' => 'kaprodi_statistika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 87,
                'name' => 'Kaprodi S2 Biologi',
                'username' => 'kaprodi_s2biologi',
                'email' => 'kaprodi_s2biologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 91,
                'name' => 'Kaprodi S2 Fisika',
                'username' => 'kaprodi_s2fisika',
                'email' => 'kaprodi_s2fisika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 104,
                'name' => 'Kaprodi S2 Kimia',
                'username' => 'kaprodi_s2kimia',
                'email' => 'kaprodi_s2kimia@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 107,
                'name' => 'Kaprodi S2 Matematika',
                'username' => 'kaprodi_s2matematika',
                'email' => 'kaprodi_s2matematika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 134,
                'name' => 'Kaprodi S3 Sains dan Matematika',
                'username' => 'kaprodi_sainsmatematika',
                'email' => 'kaprodi_sainsmatematika@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FSM

            // Start Kaprodi FK
            [
                'id' => 38,
                'name' => 'Kaprodi S1 Farmasi',
                'username' => 'kaprodi_farmasi',
                'email' => 'kaprodi_farmasi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'name' => 'Kaprodi S1 Gizi',
                'username' => 'kaprodi_gizi',
                'email' => 'kaprodi_gizi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 48,
                'name' => 'Kaprodi S1 Kedokteran',
                'username' => 'kaprodi_kedokteran',
                'email' => 'kaprodi_kedokteran@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 49,
                'name' => 'Kaprodi S1 Kedokteran Gigi',
                'username' => 'kaprodi_pskg',
                'email' => 'kaprodi_pskg@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 50,
                'name' => 'Kaprodi S1 Keperawatan',
                'username' => 'kaprodi_keperawatan',
                'email' => 'kaprodi_keperawatan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 51,
                'name' => 'Kaprodi S1 Keperawatan K. Jepara',
                'username' => 'kaprodi_keperawatan_jepara',
                'email' => 'kaprodi_keperawatan_jepara@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 93,
                'name' => 'Kaprodi S2 Ilmu Biomedis',
                'username' => 'kaprodi_s2biomedis',
                'email' => 'kaprodi_s2biomedis@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 94,
                'name' => 'Kaprodi S2 Ilmu Gizi',
                'username' => 'kaprodi_s2gizi',
                'email' => 'kaprodi_s2gizi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 101,
                'name' => 'Kaprodi S2 Keperawatan',
                'username' => 'kaprodi_s2keperawatan',
                'email' => 'kaprodi_s2keperawatan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 125,
                'name' => 'Kaprodi S3 Kedokteran dan Kesehatan',
                'username' => 'kaprodi_s3kedokteran',
                'email' => 'kaprodi_s3kedokteran@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FK

            // Start Kaprodi FH
            [
                'id' => 42,
                'name' => 'Kaprodi S1 Hukum',
                'username' => 'kaprodi_hukum',
                'email' => 'kaprodi_hukum@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 43,
                'name' => 'Kaprodi S1 Hukum K. Jepara',
                'username' => 'kaprodi_hukum_jepara',
                'email' => 'kaprodi_hukum_jepara@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 92,
                'name' => 'Kaprodi S2 Hukum',
                'username' => 'kaprodi_s2hukum',
                'email' => 'kaprodi_s2hukum@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 100,
                'name' => 'Kaprodi S2 Kenotariatan',
                'username' => 'kaprodi_s2kenotariatan',
                'email' => 'kaprodi_s2kenotariatan@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 123,
                'name' => 'Kaprodi S3 Hukum',
                'username' => 'kaprodi_s3hukum',
                'email' => 'kaprodi_s3hukum@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FH

            // Start Kaprodi FKM
            [
                'id' => 52,
                'name' => 'Kaprodi S1 Kesehatan Masyarakat',
                'username' => 'kaprodi_kesmas',
                'email' => 'kaprodi_kesmas@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 53,
                'name' => 'Kaprodi S1 Keselamatan dan Kesehatan Kerja',
                'username' => 'kaprodi_k3',
                'email' => 'kaprodi_k3@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 102,
                'name' => 'Kaprodi S2 Kesehatan Lingkungan',
                'username' => 'kaprodi_mkl',
                'email' => 'kaprodi_mkl@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 103,
                'name' => 'Kaprodi S2 Kesehatan Masyarakat',
                'username' => 'kaprodi_s2kesmas',
                'email' => 'kaprodi_s2kesmas@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 110,
                'name' => 'Kaprodi S2 Promosi Kesehatan',
                'username' => 'kaprodi_s2promkes',
                'email' => 'kaprodi_s2promkes@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 130,
                'name' => 'Kaprodi S3 Kesehatan Masyarakat',
                'username' => 'kaprodi_s3kesmas',
                'email' => 'kaprodi_s3kesmas@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi FKM

            // Start Kaprodi Fakultas Psikologi
            [
                'id' => 62,
                'name' => 'Kaprodi S1 Psikologi',
                'username' => 'kaprodi_psikologi',
                'email' => 'kaprodi_psikologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 111,
                'name' => 'Kaprodi S2 Psikologi',
                'username' => 'kaprodi_s2psikologi',
                'email' => 'kaprodi_s2psikologi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi Fakultas Psikologi

            // Start Kaprodi Sekolah Vokasi
            [
                'id' => 69,
                'name' => 'Kaprodi D4 Akuntansi Perpajakan',
                'username' => 'kaprodi_akuntasipajak',
                'email' => 'kaprodi_akuntansipajak@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 70,
                'name' => 'Kaprodi D4 Akuntansi Perpajakan K. Demak',
                'username' => 'kaprodi_akuntansipajak_demak',
                'email' => 'kaprodi_akuntansipajak_demak@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 71,
                'name' => 'Kaprodi D4 Bahasa Asing Terapan',
                'username' => 'kaprodi_bat',
                'email' => 'kaprodi_bat@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 72,
                'name' => 'Kaprodi D4 Informasi dan Humas',
                'username' => 'kaprodi_inhum',
                'email' => 'kaprodi_inhum@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 73,
                'name' => 'Kaprodi D4 Manajemen dan Administrasi Logistik',
                'username' => 'kaprodi_mal',
                'email' => 'kaprodi_mal@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 74,
                'name' => 'Kaprodi D4 Perencanaan Tata Ruang dan Pertanahan',
                'username' => 'kaprodi_ptrp',
                'email' => 'kaprodi_ptrp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 75,
                'name' => 'Kaprodi D4 Rekayasa Perancangan Mekanik',
                'username' => 'kaprodi_rpm',
                'email' => 'kaprodi_rpm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 76,
                'name' => 'Kaprodi D4 Rekayasa Perancangan Mekanik K. Demak',
                'username' => 'kaprodi_rpm_demak',
                'email' => 'kaprodi_rpm_demak@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 77,
                'name' => 'Kaprodi D4 Teknik Infrastruktur Sipil dan Perancangan Arsitektur',
                'username' => 'kaprodi_sipilarsi',
                'email' => 'kaprodi_sipilarsi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 78,
                'name' => 'Kaprodi D4 Teknil Listrik Industri',
                'username' => 'kaprodi_tli',
                'email' => 'kaprodi_tli@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 79,
                'name' => 'Kaprodi D4 Teknologi Rekayasa Kimia Industri',
                'username' => 'kaprodi_trki',
                'email' => 'kaprodi_trki@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 80,
                'name' => 'Kaprodi D4 Teknologi Rekayasa Konstruksi Perkapalan',
                'username' => 'kaprodi_trkp',
                'email' => 'kaprodi_trkp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 81,
                'name' => 'Kaprodi D4 Teknologi Rekayasa Otomasi',
                'username' => 'kaprodi_otomasi',
                'email' => 'kaprodi_otomasi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi Sekolah Vokasi

            // Start Kaprodi Sekolah Pascasarjana
            [
                'id' => 89,
                'name' => 'Kaprodi S2 Energi',
                'username' => 'kaprodi_s2energi',
                'email' => 'kaprodi_s2energi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 90,
                'name' => 'Kaprodi S1 Epidemiologi',
                'username' => 'kaprodi_s2epid',
                'email' => 'kaprodi_s2epid@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 97,
                'name' => 'Kaprodi S2 Ilmu Lingkungan',
                'username' => 'kaprodi_mil',
                'email' => 'kaprodi_mil@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 113,
                'name' => 'Kaprodi S2 Sistem Informasi',
                'username' => 'kaprodi_msi',
                'email' => 'kaprodi_msi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 127,
                'name' => 'Kaprodi S3 Ilmu Lingkungan',
                'username' => 'kaprodi_dil',
                'email' => 'kaprodi_dil@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 136,
                'name' => 'Kaprodi S3 Sistem Informasi',
                'username' => 'kaprodi_dsi',
                'email' => 'kaprodi_dsi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Kaprodi Sekolah Pascasarjana

            // Start Dekan Fakultas dan Sekolah
            [
                'id' => 150,
                'name' => 'Dekan Fakultas Hukum',
                'username' => 'dekan_fh',
                'email' => 'dekan_fh@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 151,
                'name' => 'Dekan Fakultas Ekonomi Dan Bisnis',
                'username' => 'dekan_feb',
                'email' => 'dekan_feb@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 152,
                'name' => 'Dekan Fakultas Teknik',
                'username' => 'dekan_ft',
                'email' => 'dekan_ft@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 153,
                'name' => 'Dekan Fakultas Kedokteran',
                'username' => 'dekan_fk',
                'email' => 'dekan_fk@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 154,
                'name' => 'Dekan Fakultas Peternakan Dan Pertanian',
                'username' => 'dekan_fpp',
                'email' => 'dekan_fpp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 155,
                'name' => 'Dekan Fakultas Ilmu Budaya',
                'username' => 'dekan_fib',
                'email' => 'dekan_fib@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 156,
                'name' => 'Dekan Fakultas Ilmu Sosial Dan Politik',
                'username' => 'dekan_fisip',
                'email' => 'dekan_fisip@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 157,
                'name' => 'Dekan Fakultas Kesehatan Masyarakat',
                'username' => 'dekan_fkm',
                'email' => 'dekan_fkm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 158,
                'name' => 'Dekan Fakultas Sains Dan Matematika',
                'username' => 'dekan_fsm',
                'email' => 'dekan_fsm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 159,
                'name' => 'Dekan Fakultas Perikanan Dan Ilmu Kelautan',
                'username' => 'dekan_fpik',
                'email' => 'dekan_fpik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 160,
                'name' => 'Dekan Fakultas Psikologi',
                'username' => 'dekan_fpsi',
                'email' => 'dekan_fpsi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 161,
                'name' => 'Dekan Sekolah Pascasarjana',
                'username' => 'dekan_sp',
                'email' => 'dekan_sp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 162,
                'name' => 'Dekan Sekolah Vokasi',
                'username' => 'dekan_sv',
                'email' => 'dekan_sv@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Dekan Fakultas dan Sekolah

            // Start Wakil Dekan Fakultas dan Sekolah
            [
                'id' => 163,
                'name' => 'Wakil Dekan 1 Fakultas Hukum',
                'username' => 'wadek1_fh',
                'email' => 'wadek1_fh@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 164,
                'name' => 'Wakil Dekan 1 Fakultas Ekonomi Dan Bisnis',
                'username' => 'wadek1_feb',
                'email' => 'wadek1_feb@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 165,
                'name' => 'Wakil Dekan 1 Fakultas Teknik',
                'username' => 'wadek1_ft',
                'email' => 'wadek1_ft@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 166,
                'name' => 'Wakil Dekan 1 Fakultas Kedokteran',
                'username' => 'wadek1_fk',
                'email' => 'wadek1_fk@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 167,
                'name' => 'Wakil Dekan 1 Fakultas Peternakan Dan Pertanian',
                'username' => 'wadek1_fpp',
                'email' => 'wadek1_fpp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 168,
                'name' => 'Wakil Dekan 1 Fakultas Ilmu Budaya',
                'username' => 'wadek1_fib',
                'email' => 'wadek1_fib@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 169,
                'name' => 'Wakil Dekan 1 Fakultas Ilmu Sosial Dan Politik',
                'username' => 'wadek1_fisip',
                'email' => 'wadek1_fisip@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 170,
                'name' => 'Wakil Dekan 1 Fakultas Kesehatan Masyarakat',
                'username' => 'wadek1_fkm',
                'email' => 'wadek1_fkm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 171,
                'name' => 'Wakil Dekan 1 Fakultas Sains Dan Matematika',
                'username' => 'wadek1_fsm',
                'email' => 'wadek1_fsm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 172,
                'name' => 'Wakil Dekan 1 Fakultas Perikanan Dan Ilmu Kelautan',
                'username' => 'wadek1_fpik',
                'email' => 'wadek1_fpik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 173,
                'name' => 'Wakil Dekan 1 Fakultas Psikologi',
                'username' => 'wadek1_fpsi',
                'email' => 'wadek1_fpsi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 174,
                'name' => 'Wakil Dekan 1 Sekolah Pascasarjana',
                'username' => 'wadek1_sp',
                'email' => 'wadek1_sp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 175,
                'name' => 'Wakil Dekan 1 Sekolah Vokasi',
                'username' => 'wadek1_sv',
                'email' => 'wadek1_sv@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Wakil Dekan Fakultas dan Sekolah

            // Start Wakil Rektor 1 Universitas Diponegoro
            [
                'id' => 180,
                'name' => 'Wakil Rektor 1 Universitas Diponegoro',
                'username' => 'warek1',
                'email' => 'warek1@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End Wakil Rektor 1 Universitas Diponegoro

            // Start TPMF Fakultas dan Sekolah
            [
                'id' => 181,
                'name' => 'TPMF Fakultas Ekonomi Dan Bisnis',
                'username' => 'tpmf_feb',
                'email' => 'tpmf_feb@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 182,
                'name' => 'TPMF Fakultas Teknik',
                'username' => 'tpmf_ft',
                'email' => 'tpmf_ft@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 183,
                'name' => 'TPMF Fakultas Kedokteran',
                'username' => 'tpmf_fk',
                'email' => 'tpmf_fk@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 184,
                'name' => 'TPMF Fakultas Peternakan Dan Pertanian',
                'username' => 'tpmf_fpp',
                'email' => 'tpmf_fpp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 185,
                'name' => 'TPMF Fakultas Ilmu Budaya',
                'username' => 'tpmf_fib',
                'email' => 'tpmf_fib@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 186,
                'name' => 'TPMF Fakultas Ilmu Sosial Dan Ilmu Politik',
                'username' => 'tpmf_fisip',
                'email' => 'tpmf_fisip@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 187,
                'name' => 'TPMF Fakultas Masyarakat',
                'username' => 'tpmf_fkm',
                'email' => 'tpmf_fkm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 188,
                'name' => 'TPMF Fakultas Sains Dan Matematika',
                'username' => 'tpmf_fsm',
                'email' => 'tpmf_fsm@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 189,
                'name' => 'TPMF Fakultas Perikanan Dan Ilmu Kelautan',
                'username' => 'tpmf_fpik',
                'email' => 'tpmf_fpik@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 190,
                'name' => 'TPMF Fakultas Psikologi',
                'username' => 'tpmf_fpsi',
                'email' => 'tpmf_fpsi@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 191,
                'name' => 'TPMF Sekolah Pascarsarjana',
                'username' => 'tpmf_sp',
                'email' => 'tpmf_sp@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 192,
                'name' => 'TPMF Sekolah Vokasi',
                'username' => 'tpmf_sv',
                'email' => 'tpmf_sv@gmail.com',
                'password' => Hash::make('undip123'),
                'image' => 'tes.png',
                'status' => 1,
                'last_login' => null,
                'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            // End TPMF Fakultas dan Sekolah

        ];

        User::insert($data);
    }
}
